### PR TITLE
feat: Add a variable to control border color of the codes selector divider

### PR DESCRIPTION
**Pull request by deiteris**

### CODE REVIEW

**Review by carowright — DISMISSED** [review]
LGTM!

**Comment by deiteris** [comment]
Good. When it will be merged? And what about https://github.com/advanced-rest-client/api-responses-document/issues/20?

**Comment by TwoPlusTwoOne** [comment]
Hi @deiteris I left a comment in #20 

Could you please bump the version? Then I'll merge it

**Comment by deiteris** [comment]
Done.

**Comment by deiteris** [comment]
@TwoPlusTwoOne any ETA for this? I see you created https://github.com/advanced-rest-client/api-responses-document/pull/23 that bumps the version too and it will create a conflict with this PR.

**Comment by TwoPlusTwoOne** [comment]
Apologies for the delay. I'll merge this and bump the version in my other PR

**Review by TwoPlusTwoOne — APPROVED** [review]

**Pull request merged**
